version: '3.7'
services:
  database:
    container_name: postgres
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  app:
    container_name: application
    depends_on:
      - database
    ports:
      - '3000:3000'
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: on-failure
