apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres-container
      image: postgres:11
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: 'database'
        - name: POSTGRES_HOST
          value: 'database'
        - name: POSTGRES_USER
          value: 'root'
        - name: POSTGRES_PASSWORD
          value: 'root'
