apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-postgres
spec:
  serviceName: database
  replicas: 2
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:11
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "database"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGREs_HOST
              value: "localhost"
            - name: POSTGRES_PASSWORD
              value: "root"
          volumeMounts:
            - name: postgres-volume
              mounthPath: /var/lib/postgresql/data
          volumes:
            - name: postgres-volume
              persistentVolumeClaim:
                claimName: postgres-config
