apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/data/postgres-pv'
